/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.TaiKhoan;
import model.TaiKhoanModel;


public class DangNhapform extends javax.swing.JFrame {

    /**
     * Creates new form DangKy
     */
    private TaiKhoanModel tkm;
    DangKyform form;
    ArrayList<TaiKhoan> list;

    public DangNhapform() {
        initComponents();
        this.setTitle("Đăng nhập Form");
        tkm = new TaiKhoanModel();
        list = tkm.getDstk();
        tkm.fakedata();

        this.setLocationRelativeTo(null);
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_cout = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_taikhoandn = new javax.swing.JTextField();
        btn_dangky = new javax.swing.JButton();
        btn_dangnhap = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        check_xacnhan = new javax.swing.JCheckBox();
        txt_matkhaudn = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_cout.setBackground(new java.awt.Color(255, 204, 204));
        lb_cout.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tài khoản  :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Mật khẩu  :");

        btn_dangky.setBackground(new java.awt.Color(255, 255, 102));
        btn_dangky.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_dangky.setForeground(new java.awt.Color(0, 153, 51));
        btn_dangky.setText("Đăng ký");
        btn_dangky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangkyActionPerformed(evt);
            }
        });

        btn_dangnhap.setBackground(new java.awt.Color(255, 255, 0));
        btn_dangnhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_dangnhap.setForeground(new java.awt.Color(0, 153, 51));
        btn_dangnhap.setText("Đăng nhập");
        btn_dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangnhapActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("ĐĂNG NHẬP Ở ĐÂY !");

        check_xacnhan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        check_xacnhan.setForeground(new java.awt.Color(0, 153, 153));
        check_xacnhan.setText("Xác nhận tại đây");
        check_xacnhan.setActionCommand("Xác nhận ");
        check_xacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_xacnhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lb_coutLayout = new javax.swing.GroupLayout(lb_cout);
        lb_cout.setLayout(lb_coutLayout);
        lb_coutLayout.setHorizontalGroup(
            lb_coutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lb_coutLayout.createSequentialGroup()
                .addGroup(lb_coutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lb_coutLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(lb_coutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lb_coutLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btn_dangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(btn_dangky, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(lb_coutLayout.createSequentialGroup()
                                .addGroup(lb_coutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(77, 77, 77)
                                .addGroup(lb_coutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_taikhoandn, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(txt_matkhaudn)))))
                    .addGroup(lb_coutLayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(check_xacnhan))
                    .addGroup(lb_coutLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel3)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        lb_coutLayout.setVerticalGroup(
            lb_coutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lb_coutLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(lb_coutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_taikhoandn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(lb_coutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_matkhaudn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(check_xacnhan)
                .addGap(31, 31, 31)
                .addGroup(lb_coutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_dangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_dangky, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );

        jMenu1.setBackground(new java.awt.Color(204, 204, 0));
        jMenu1.setText("Among ");
        jMenu1.setMinimumSize(new java.awt.Dimension(35, 30));

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jMenuItem1.setActionCommand("Nguyễn Thị Phương Anh");
        jMenuItem1.setLabel("Nguyễn Thị Phương Anh");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jMenuItem2.setText("Phùng Thị Giang");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jMenuItem3.setText("Nguyễn Thu Hồng");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jMenuItem4.setText("Bùi Thị Lan");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jMenuItem5.setText("Dương Thị Hồng Vân");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_cout, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_cout, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dangkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangkyActionPerformed
        // TODO add your handling code here:
        form = new DangKyform();
        this.dispose();
        form.setVisible(true);

    }//GEN-LAST:event_btn_dangkyActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void btn_dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangnhapActionPerformed
        // TODO add your handling code here:

        if (check_xacnhan.isSelected()) {
    try {
        TaiKhoan tk = new TaiKhoan();
        String taikhoan = txt_taikhoandn.getText();
        String matkhau = txt_matkhaudn.getText();
        if (dangnhap(tk)) {
            JOptionPane.showMessageDialog(rootPane, "Đăng nhập thành công", "Welcome!!!", HEIGHT);
            QLTTthanhvienform form = new QLTTthanhvienform();
            form.setVisible(true);
            form.setLocationRelativeTo(null);
        } else {
            if (taikhoan.equals("") || matkhau.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng điền đầy đủ thông tin", "THÔNG BÁO", HEIGHT);
                check_xacnhan.setSelected(false);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Tài khoản hoặc mật khẩu của bạn không đúng!", "THÔNG BÁO️", HEIGHT);
                txt_matkhaudn.setText("");
                txt_taikhoandn.setText("");
                check_xacnhan.setSelected(false);
            }
        }
    } catch (Exception e) {
        // Xử lý lỗi tại đây
        JOptionPane.showMessageDialog(rootPane, "LỖI THÔNG TIN", "THÔNG BÁO", HEIGHT);
        e.printStackTrace();
    }
} else {
    JOptionPane.showMessageDialog(rootPane, "Bạn chưa xác nhận", "THÔNG BÁO", HEIGHT);
    check_xacnhan.setSelected(false);
}
    }//GEN-LAST:event_btn_dangnhapActionPerformed

    private void check_xacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_xacnhanActionPerformed
        // TODO add your handling code here:
        TaiKhoan tk = new TaiKhoan();
        if (evt.getActionCommand().equals("Xác nhận đăng nhập")) {
            //   dangnhap(tk)=true;
        }

    }//GEN-LAST:event_check_xacnhanActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    public boolean dangnhap(TaiKhoan tk) {
        try {
        String taikhoan = txt_taikhoandn.getText();
        String matkhau = txt_matkhaudn.getText();
        tk = new TaiKhoan(taikhoan, matkhau);

        for (TaiKhoan taiKhoan : list) {
            if (taiKhoan.getTaikhoan().equals(taikhoan) && taiKhoan.getMatkhau().equals(matkhau)) {
                return true;
            }
        }
    } catch (Exception e) {
        // Xử lý lỗi tại đây
        JOptionPane.showMessageDialog(rootPane, "LỖI THÔNG TIN", "THÔNG BÁO", HEIGHT);
        e.printStackTrace();
    }
    return false;
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhapform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangky;
    private javax.swing.JButton btn_dangnhap;
    private javax.swing.JCheckBox check_xacnhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel lb_cout;
    private javax.swing.JPasswordField txt_matkhaudn;
    private javax.swing.JTextField txt_taikhoandn;
    // End of variables declaration//GEN-END:variables

    void updateTable() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
