/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.TaiKhoan;
import model.TaiKhoanModel;

public class DangKyform extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    private TaiKhoanModel tkm;
    DangNhapform form = new DangNhapform();
    ArrayList<TaiKhoan> list = form.list;

    public DangKyform() {
        initComponents();
        this.setTitle("Đăng ký Form");
        tkm = new TaiKhoanModel();
        tkm.fakedata();

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_taikhoandki = new javax.swing.JTextField();
        txt_matkhaudangky = new javax.swing.JTextField();
        txt_matkhauxacnhan = new javax.swing.JTextField();
        btn_dangky = new javax.swing.JButton();
        btn_huy = new javax.swing.JButton();
        check_chapnhan = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tài khoản :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Mật khẩu :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Xác nhận mật khẩu :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Đăng ký sổ tay cá nhân giáo viên");

        btn_dangky.setBackground(new java.awt.Color(255, 255, 0));
        btn_dangky.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_dangky.setText("Đăng ký");
        btn_dangky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangkyActionPerformed(evt);
            }
        });

        btn_huy.setBackground(new java.awt.Color(255, 255, 0));
        btn_huy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_huy.setText("Hủy bỏ");
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        check_chapnhan.setBackground(new java.awt.Color(255, 153, 153));
        check_chapnhan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        check_chapnhan.setText("Chấp nhận điều khoản");
        check_chapnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_chapnhanActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("BỘ CÔNG THƯƠNG");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("ĐẠI HỌC CÔNG NGHIỆP HÀ NỘI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_taikhoandki, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(txt_matkhaudangky)
                            .addComponent(txt_matkhauxacnhan)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btn_dangky)
                        .addGap(85, 85, 85)
                        .addComponent(btn_huy))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(check_chapnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_taikhoandki, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_matkhaudangky, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_matkhauxacnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(check_chapnhan)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_dangky, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_huy, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        // TODO add your handling code here:
        this.dispose();

//        form.setVisible(true);
//        form.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_huyActionPerformed

    private void btn_dangkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangkyActionPerformed
        // TODO add your handling code here:       
        if (check_chapnhan.isSelected()) {
            try{
            String taikhoandk = txt_taikhoandki.getText();
            String mkhaudki = txt_matkhaudangky.getText();
            String mkxacnhan = txt_matkhauxacnhan.getText();
            TaiKhoan tk = new TaiKhoan();
            if (dangky(tk)) {
                JOptionPane.showMessageDialog(rootPane, "Đăng ký thành công", "Chúc mừng bạn", HEIGHT);
                this.dispose();
            } else {

                if (taikhoandk.equals("") || mkhaudki.equals("") || mkxacnhan.equals("")) {
                    JOptionPane.showMessageDialog(rootPane, "Vui lòng điền đầy đủ thông tin", "Notification!", HEIGHT);
                    check_chapnhan.setSelected(false);
                } else if (!mkhaudki.equals(mkxacnhan)) {
                    JOptionPane.showMessageDialog(rootPane, "Mật khẩu chưa đúng", "Thông báo", HEIGHT);
                    txt_matkhaudangky.setText("");
                    txt_matkhauxacnhan.setText("");
                    
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Tài khoản đã tồn tại,vui lòng nhập lại", "Thông báo", HEIGHT);
                    check_chapnhan.setSelected(false);
                    txt_matkhaudangky.setText("");
                    txt_matkhauxacnhan.setText("");
                    txt_taikhoandki.setText("");
                }
            }
            }
            catch (Exception e) {
            // Xử lý ngoại lệ tại đây
            JOptionPane.showMessageDialog(rootPane, "Lỗi đăng ký tài khoản:\n" + e.getMessage(), "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            }    
        } else {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa xác nhận đăng ký", "Thông báo", HEIGHT);
            check_chapnhan.setSelected(false);
        }        
    }//GEN-LAST:event_btn_dangkyActionPerformed

    private void check_chapnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_chapnhanActionPerformed
        // TODO add your handling code here:
        if (check_chapnhan.isSelected()) {
        btn_dangky.setEnabled(true);
       } else {
        btn_dangky.setEnabled(false);
       }       
    }//GEN-LAST:event_check_chapnhanActionPerformed
    public boolean dangky(TaiKhoan tk) {          
        String taikhoandk = txt_taikhoandki.getText();
        String mkhaudki = txt_matkhaudangky.getText();
        String mkxacnhan = txt_matkhauxacnhan.getText();
        ArrayList<TaiKhoan> list = form.list;
        //kiem tra ten tai khoan da ton tai trong danh sach hay chưa
        for (TaiKhoan taiKhoan : list) {
            if (taiKhoan.getTaikhoan().equals(taikhoandk)) {
                return false;
            }
        }
        //kiem tra cac truong thong tin tai khoan
        if (taikhoandk.equals("") || mkhaudki.equals("") || mkxacnhan.equals("")) {
            return false;
        }
        //kiem tra mat khau va mat khau xac thuc co khop hay khong
        if (!mkhaudki.equals(mkxacnhan)) {
            return false;
        }
        try {
        // Tạo mới đối tượng tài khoản và thêm vào danh sách
        TaiKhoan newTaiKhoan = new TaiKhoan(taikhoandk, mkhaudki);
        list.add(newTaiKhoan);
        return true;
    } catch (Exception ex) {
        // Nếu có lỗi xảy ra, in ra thông tin lỗi và trả về false        
        ex.printStackTrace();
        return false;
    }
            /*tk = new TaiKhoan(taikhoandk, mkhaudki);
            list.add(tk);

            return true;
        }
        return false;8*/
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKyform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKyform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKyform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKyform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DangKyform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangky;
    private javax.swing.JButton btn_huy;
    private javax.swing.JCheckBox check_chapnhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_matkhaudangky;
    private javax.swing.JTextField txt_matkhauxacnhan;
    private javax.swing.JTextField txt_taikhoandki;
    // End of variables declaration//GEN-END:variables

    
}
