/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import java.awt.event.KeyEvent;
import static java.awt.image.ImageObserver.HEIGHT;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HoatDong;
import model.HoatDongModel;
import model.ThanhVien;


public class QuanLyhoatdongform extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyhoatdongform
     */
    private HoatDongModel hdm;
    ArrayList<HoatDong> list;
    DefaultTableModel tb_model;

    public QuanLyhoatdongform() {
        initComponents();
        tb_model = (DefaultTableModel) this.tb_danhsach.getModel();

        hdm = new HoatDongModel();
        hdm.fakedata();
        list = hdm.getDshd();
        hienthidsfake();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_danhsach = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_kinhphi = new javax.swing.JTextField();
        txt_tenhd = new javax.swing.JTextField();
        txt_mahd = new javax.swing.JTextField();
        txt_diadiem = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_sl = new javax.swing.JTextField();
        btn_reset = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tb_danhsach.setBackground(new java.awt.Color(204, 204, 204));
        tb_danhsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HĐ", "Tên HĐ", "Địa điểm", "Số lượng tham gia", "Kinh phí"
            }
        ));
        jScrollPane1.setViewportView(tb_danhsach);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Mã HĐ: ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Địa điểm: ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Tên HĐ           :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Kinh phí           :");

        btn_back.setBackground(new java.awt.Color(153, 204, 0));
        btn_back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_back.setText("Thoát");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("SL tham gia     :");

        btn_reset.setBackground(new java.awt.Color(153, 204, 0));
        btn_reset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_them.setBackground(new java.awt.Color(153, 204, 0));
        btn_them.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_xoa.setBackground(new java.awt.Color(153, 204, 0));
        btn_xoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_mahd, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(txt_diadiem)
                            .addComponent(txt_sl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_them)
                        .addGap(81, 81, 81)
                        .addComponent(btn_xoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(btn_reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_kinhphi, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tenhd, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btn_back)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mahd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tenhd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_diadiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kinhphi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_sl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_xoa)
                    .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_back))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Quản Lý Hoạt Động");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void resetform() {
        txt_mahd.setText("");
        txt_diadiem.setText("");
        txt_kinhphi.setText("");
        txt_tenhd.setText("");
        txt_sl.setText("");

    }

    public void setModel(HoatDong hd) {
        hd.setMahd(txt_mahd.getText());
        hd.setTenhd(txt_tenhd.getText());
        hd.setDiadiem(txt_diadiem.getText());
        try {
            hd.setKinhphi(Long.parseLong(txt_kinhphi.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Kinh phí phải là số", "Thông báo", HEIGHT);
        }
        try {
            hd.setSoluong(Integer.parseInt(txt_sl.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Số lưởng phải là kiểu số nguyên", "Thông báo", HEIGHT);
        }
    }

    public int add(HoatDong hd) {
        boolean ok = true;
        try {

        } catch (Exception e) {
        }
        for (HoatDong hoatDong : list) {
            if (hoatDong.equals(hd)) {
                return -1;

            } else {
                setModel(hd);
            }
        }
        return 1;
    }

    public void themvaods(HoatDong hd) {

        tb_model.addRow(new Object[]{
            hd.getMahd(),
            hd.getTenhd(),
            hd.getDiadiem(),
            hd.getSoluong(),
            hd.getKinhphi(),});

    }

    public void hienthidsfake() {
        for (HoatDong hoatDong : list) {
            tb_model.addRow(new Object[]{
                hoatDong.getMahd(),
                hoatDong.getTenhd(),
                hoatDong.getDiadiem(),
                hoatDong.getSoluong(),
                hoatDong.getKinhphi(),});
        }
    }
    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        if (txt_diadiem.getText().isEmpty() || txt_kinhphi.getText().isEmpty() || txt_mahd.getText().isEmpty() || txt_tenhd.getText().isEmpty() || txt_sl.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Bạn cần diền đầy đủ thông tin", "Thông báo", HEIGHT);
        } else {
            HoatDong hd = new HoatDong();
            add(hd);
            if (add(hd) == 1) {
                JOptionPane.showMessageDialog(rootPane, "Thêm thành công", "Thông báo", HEIGHT);
                list.add(hd);
                themvaods(hd);
                resetform();
            } else {
                if (hdm.findhd(txt_mahd.getText()) != null) {
                    JOptionPane.showMessageDialog(rootPane, "Hoạt dộng này đã tồn tại", "Thông báo", HEIGHT);
                    resetform();
                } else {

                }
            }
        }

    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        resetform();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        String mhd = txt_mahd.getText();
        HoatDong hd = hdm.findhd(mhd);
        
        if (kiemtratontai(mhd)<0) {
            hdm.xoa(mhd);
            xoatvtrongds(hd);
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập mã hd", "Thông báo", HEIGHT);
            resetForm();
        } else {
            if (mhd.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Xóa thành công", "Thông báo", HEIGHT);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Hoạt động ko tồn tại", "Thông báo", HEIGHT);
         
  resetForm();
            }
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

     

       
        
                                        
 public void xoatvtrongds(HoatDong hd) {
        int rowcount = tb_danhsach.getRowCount();
        int indexrow = -1;
        String mhd = hd.getMahd();
        for (int i = 0; i < rowcount; i++) {
            //tim msv can xoa trong table
            String value = tb_model.getValueAt(i, 0).toString();
            if (value.equals(mhd)) {
                indexrow = i;
                break;
            }
        }
        if (indexrow >= 0) {
            tb_model.removeRow(indexrow);

        }
    }
    public int kiemtratontai(String mhd) {
        mhd = txt_mahd.getText();
        for (HoatDong hoatDong : list) {
            if (hoatDong.getMahd().equals(mhd)) {
                return -1;
            }
        }
        return 1;
    }
     public void resetForm(){
      txt_mahd.setText("");
      txt_tenhd.setText("");
      txt_diadiem.setText("");
      txt_kinhphi.setText(String.valueOf(""));
      txt_sl.setText(String.valueOf(""));
}
    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        String src = evt.getActionCommand();
        btn_back.setMnemonic(KeyEvent.VK_E);
        if (src.equals("Thoát")) {
            int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc muốn thoát không?", "Thông báo", WIDTH);
            if (choice == JOptionPane.OK_OPTION) {
                JOptionPane.showMessageDialog(rootPane, "❤Tạm biệt bạn nhé! Hẹn gặp lại :3❤️", "===️", HEIGHT);
                this.dispose();
            }

        }
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyhoatdongform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyhoatdongform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyhoatdongform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyhoatdongform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new QuanLyhoatdongform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_danhsach;
    private javax.swing.JTextField txt_diadiem;
    private javax.swing.JTextField txt_kinhphi;
    private javax.swing.JTextField txt_mahd;
    private javax.swing.JTextField txt_sl;
    private javax.swing.JTextField txt_tenhd;
    // End of variables declaration//GEN-END:variables

    private void setTV(ThanhVien tv) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void setTV(HoatDong tv) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
